export const ROUTES_PATHS = {
  HOME: "/",
  POLICY: "/privacy-policy",
  FENCE: "/fence",
  FENCEFORM: "/questionnaire",
  WATER: "/water",
  FAUNDATION: "/foundation",
  TOPOGRAPHY: "/topography",
  ELECTRICITY: "/electricity",
  DRAINAGE: "/drainage",
  SERVICE: "/service",
  DEPARTURE: "/departure",
  LANDSCAPE: "/landscape",
  DEVELOP: "/develop",
  VACANCIES: "/vacancies-junior",
  VACANCIES_MID: "/vacancies-middle",
  SEPTIC: "/septic",
  CALENDARSERVICE: "/calendar-service",
};
